/**
 * @file database.generated.ts
 * @description Auto-generated database schema definitions for the UDBHAV Foundation platform.
 */

/**
 * Valid JSON type representation for database JSON/JSONB columns.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Root database interface defining tables, views, functions, and enums for the public schema.
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          role: string;
          first_name: string | null;
          last_name: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id: string;
          email: string;
          role?: string;
          first_name?: string | null;
          last_name?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          first_name?: string | null;
          last_name?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      programs: {
        Row: {
          id: string;
          program_code: string;
          slug: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          status: string;
          visibility: string;
          cover_image_id: string | null;
          start_date: string | null;
          end_date: string | null;
          is_featured: boolean;
          display_order: number;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          program_code: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          status?: string;
          visibility?: string;
          cover_image_id?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          is_featured?: boolean;
          display_order?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          program_code?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          status?: string;
          visibility?: string;
          cover_image_id?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          is_featured?: boolean;
          display_order?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      events: {
        Row: {
          id: string;
          program_id: string;
          event_code: string;
          slug: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          status: string;
          visibility: string;
          event_type: string;
          venue_name: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          latitude: number | null;
          longitude: number | null;
          start_time: string | null;
          end_time: string | null;
          max_attendees: number | null;
          registered_count: number;
          is_featured: boolean;
          cover_image_id: string | null;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          program_id: string;
          event_code: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          status?: string;
          visibility?: string;
          event_type?: string;
          venue_name?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          start_time?: string | null;
          end_time?: string | null;
          max_attendees?: number | null;
          registered_count?: number;
          is_featured?: boolean;
          cover_image_id?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          program_id?: string;
          event_code?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          status?: string;
          visibility?: string;
          event_type?: string;
          venue_name?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          start_time?: string | null;
          end_time?: string | null;
          max_attendees?: number | null;
          registered_count?: number;
          is_featured?: boolean;
          cover_image_id?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      volunteer_profiles: {
        Row: {
          id: string;
          profile_id: string;
          volunteer_code: string;
          status: string;
          skills: string[];
          interests: string[];
          availability: string;
          total_hours_served: number;
          events_attended_count: number;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          profile_id: string;
          volunteer_code: string;
          status?: string;
          skills?: string[];
          interests?: string[];
          availability?: string;
          total_hours_served?: number;
          events_attended_count?: number;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          profile_id?: string;
          volunteer_code?: string;
          status?: string;
          skills?: string[];
          interests?: string[];
          availability?: string;
          total_hours_served?: number;
          events_attended_count?: number;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      event_volunteers: {
        Row: {
          id: string;
          event_id: string;
          volunteer_profile_id: string;
          role: string;
          status: string;
          hours_awarded: number;
          check_in_time: string | null;
          check_out_time: string | null;
          feedback: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          event_id: string;
          volunteer_profile_id: string;
          role?: string;
          status?: string;
          hours_awarded?: number;
          check_in_time?: string | null;
          check_out_time?: string | null;
          feedback?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          event_id?: string;
          volunteer_profile_id?: string;
          role?: string;
          status?: string;
          hours_awarded?: number;
          check_in_time?: string | null;
          check_out_time?: string | null;
          feedback?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      news_articles: {
        Row: {
          id: string;
          article_code: string;
          slug: string;
          title: string;
          subtitle: string | null;
          content: string;
          summary: string | null;
          cover_image_id: string | null;
          author_profile_id: string | null;
          status: string;
          visibility: string;
          published_at: string | null;
          is_featured: boolean;
          view_count: number;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          article_code: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          content: string;
          summary?: string | null;
          cover_image_id?: string | null;
          author_profile_id?: string | null;
          status?: string;
          visibility?: string;
          published_at?: string | null;
          is_featured?: boolean;
          view_count?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          article_code?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          content?: string;
          summary?: string | null;
          cover_image_id?: string | null;
          author_profile_id?: string | null;
          status?: string;
          visibility?: string;
          published_at?: string | null;
          is_featured?: boolean;
          view_count?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      success_stories: {
        Row: {
          id: string;
          story_code: string;
          slug: string;
          title: string;
          subtitle: string | null;
          content: string;
          beneficiary_name: string | null;
          program_id: string | null;
          event_id: string | null;
          cover_image_id: string | null;
          status: string;
          visibility: string;
          published_at: string | null;
          is_featured: boolean;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          story_code: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          content: string;
          beneficiary_name?: string | null;
          program_id?: string | null;
          event_id?: string | null;
          cover_image_id?: string | null;
          status?: string;
          visibility?: string;
          published_at?: string | null;
          is_featured?: boolean;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          story_code?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          content?: string;
          beneficiary_name?: string | null;
          program_id?: string | null;
          event_id?: string | null;
          cover_image_id?: string | null;
          status?: string;
          visibility?: string;
          published_at?: string | null;
          is_featured?: boolean;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      gallery_albums: {
        Row: {
          id: string;
          album_code: string;
          slug: string;
          title: string;
          description: string | null;
          cover_image_id: string | null;
          program_id: string | null;
          event_id: string | null;
          visibility: string;
          display_order: number;
          is_featured: boolean;
          item_count: number;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          album_code: string;
          slug: string;
          title: string;
          description?: string | null;
          cover_image_id?: string | null;
          program_id?: string | null;
          event_id?: string | null;
          visibility?: string;
          display_order?: number;
          is_featured?: boolean;
          item_count?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          album_code?: string;
          slug?: string;
          title?: string;
          description?: string | null;
          cover_image_id?: string | null;
          program_id?: string | null;
          event_id?: string | null;
          visibility?: string;
          display_order?: number;
          is_featured?: boolean;
          item_count?: number;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      gallery_items: {
        Row: {
          id: string;
          album_id: string;
          media_id: string;
          title: string | null;
          caption: string | null;
          display_order: number;
          is_featured: boolean;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          album_id: string;
          media_id: string;
          title?: string | null;
          caption?: string | null;
          display_order?: number;
          is_featured?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          album_id?: string;
          media_id?: string;
          title?: string | null;
          caption?: string | null;
          display_order?: number;
          is_featured?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      media_objects: {
        Row: {
          id: string;
          filename: string;
          r2_key: string;
          bucket: string;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          duration: number | null;
          public_url: string;
          title: string | null;
          alt_text: string | null;
          caption: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          filename: string;
          r2_key: string;
          bucket: string;
          mime_type: string;
          size_bytes: number;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          public_url: string;
          title?: string | null;
          alt_text?: string | null;
          caption?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          filename?: string;
          r2_key?: string;
          bucket?: string;
          mime_type?: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          public_url?: string;
          title?: string | null;
          alt_text?: string | null;
          caption?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      donations: {
        Row: {
          id: string;
          donation_number: string;
          donor_id: string;
          amount: number;
          currency: string;
          status: string;
          payment_method: string | null;
          provider: string;
          gateway_transaction_id: string | null;
          gateway_order_id: string | null;
          donation_type: string;
          program_id: string | null;
          campaign_id: string | null;
          notes: string | null;
          receipt_number: string | null;
          receipt_issued_at: string | null;
          is_80g_eligible: boolean;
          is_anonymous: boolean;
          paid_at: string | null;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          donation_number: string;
          donor_id: string;
          amount: number;
          currency: string;
          status: string;
          payment_method?: string | null;
          provider?: string;
          gateway_transaction_id?: string | null;
          gateway_order_id?: string | null;
          donation_type: string;
          program_id?: string | null;
          campaign_id?: string | null;
          notes?: string | null;
          receipt_number?: string | null;
          receipt_issued_at?: string | null;
          is_80g_eligible?: boolean;
          is_anonymous?: boolean;
          paid_at?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          donation_number?: string;
          donor_id?: string;
          amount?: number;
          currency?: string;
          status?: string;
          payment_method?: string | null;
          provider?: string;
          gateway_transaction_id?: string | null;
          gateway_order_id?: string | null;
          donation_type?: string;
          program_id?: string | null;
          campaign_id?: string | null;
          notes?: string | null;
          receipt_number?: string | null;
          receipt_issued_at?: string | null;
          is_80g_eligible?: boolean;
          is_anonymous?: boolean;
          paid_at?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      donation_campaigns: {
        Row: {
          id: string;
          campaign_code: string;
          slug: string;
          title: string;
          subtitle: string | null;
          description: string | null;
          goal_amount: number;
          raised_amount: number;
          currency: string;
          start_date: string | null;
          end_date: string | null;
          status: string;
          visibility: string;
          cover_image_id: string | null;
          program_id: string | null;
          is_featured: boolean;
          donor_count: number;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          campaign_code: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          description?: string | null;
          goal_amount: number;
          raised_amount?: number;
          currency?: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          visibility?: string;
          cover_image_id?: string | null;
          program_id?: string | null;
          is_featured?: boolean;
          donor_count?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          campaign_code?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          description?: string | null;
          goal_amount?: number;
          raised_amount?: number;
          currency?: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          visibility?: string;
          cover_image_id?: string | null;
          program_id?: string | null;
          is_featured?: boolean;
          donor_count?: number;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      donors: {
        Row: {
          id: string;
          profile_id: string | null;
          first_name: string | null;
          last_name: string | null;
          organization_name: string | null;
          email: string;
          phone: string | null;
          pan_number: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          is_anonymous: boolean;
          total_donated: number;
          donation_count: number;
          first_donated_at: string | null;
          last_donated_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          organization_name?: string | null;
          email: string;
          phone?: string | null;
          pan_number?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          is_anonymous?: boolean;
          total_donated?: number;
          donation_count?: number;
          first_donated_at?: string | null;
          last_donated_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          organization_name?: string | null;
          email?: string;
          phone?: string | null;
          pan_number?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          is_anonymous?: boolean;
          total_donated?: number;
          donation_count?: number;
          first_donated_at?: string | null;
          last_donated_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      contacts: {
        Row: {
          id: string;
          profile_id: string | null;
          full_name: string;
          organization: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          country: string;
          website: string | null;
          social_links: Record<string, unknown>;
          preferred_contact_method: string;
          preferred_language: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          full_name: string;
          organization?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country: string;
          website?: string | null;
          social_links?: Record<string, unknown>;
          preferred_contact_method: string;
          preferred_language?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          full_name?: string;
          organization?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string;
          website?: string | null;
          social_links?: Record<string, unknown>;
          preferred_contact_method?: string;
          preferred_language?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      enquiries: {
        Row: {
          id: string;
          enquiry_number: string;
          contact_id: string;
          subject: string;
          message: string;
          department: string;
          status: string;
          priority: string;
          channel: string | null;
          assigned_to: string | null;
          assigned_by: string | null;
          assignment_time: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          first_response_time: number | null;
          ip_address: string | null;
          user_agent: string | null;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          enquiry_number: string;
          contact_id: string;
          subject: string;
          message: string;
          department: string;
          status: string;
          priority: string;
          channel?: string | null;
          assigned_to?: string | null;
          assigned_by?: string | null;
          assignment_time?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          first_response_time?: number | null;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          enquiry_number?: string;
          contact_id?: string;
          subject?: string;
          message?: string;
          department?: string;
          status?: string;
          priority?: string;
          channel?: string | null;
          assigned_to?: string | null;
          assigned_by?: string | null;
          assignment_time?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          first_response_time?: number | null;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_data: Record<string, unknown> | null;
          new_data: Record<string, unknown> | null;
          ip_address: string | null;
          user_agent: string | null;
          request_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_data?: Record<string, unknown> | null;
          new_data?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          old_data?: Record<string, unknown> | null;
          new_data?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          request_id?: string | null;
          created_at?: string;
        };
      };
      lookup_taxonomy: {
        Row: {
          id: string;
          taxonomy_type: string;
          code: string;
          label: string;
          description: string | null;
          parent_id: string | null;
          display_order: number;
          is_enabled: boolean;
          metadata: Record<string, unknown>;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          taxonomy_type: string;
          code: string;
          label: string;
          description?: string | null;
          parent_id?: string | null;
          display_order?: number;
          is_enabled?: boolean;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          taxonomy_type?: string;
          code?: string;
          label?: string;
          description?: string | null;
          parent_id?: string | null;
          display_order?: number;
          is_enabled?: boolean;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      system_settings: {
        Row: {
          id: string;
          setting_key: string;
          setting_value: unknown;
          setting_group: string;
          description: string | null;
          is_public: boolean;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          id?: string;
          setting_key: string;
          setting_value: unknown;
          setting_group: string;
          description?: string | null;
          is_public?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          id?: string;
          setting_key?: string;
          setting_value?: unknown;
          setting_group?: string;
          description?: string | null;
          is_public?: boolean;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
}
